added possibility to stop objects
ipa320/cob_simulation pull request #122
Opened 2016-11-10 12:44 UTC by fmw-hb

objects that are moving stop when too close to a chosen object (-o --object)

works at the moment only for linear motion

(sorry for the 2 unnecessary commits, couldn't rebase)

2016-11-21 07:57 UTC, ipa-fmw commented on cob_bringup_sim/scripts/move_object.py
> +            if(model_dist > 2):
please introduce a parameter `stop_distance` with default = 2.

2016-11-21 07:58 UTC, ipa-fmw commented on cob_bringup_sim/scripts/move_object.py
> +            model_dist = 5;
should be `model_dist = stop_distance`

2016-11-21 08:12 UTC, ipa-fmw commented on cob_bringup_sim/scripts/move_object.py
> +        parser.add_option("-o", "--object",
please rename to `stop_objects` (plural) as a list of strings and change code to check against all objects in the list.

2016-11-21 08:12 UTC, floweisshardt requested changes
see inline comments

2016-12-09 10:28 UTC, ipa-fxm commented on cob_bringup_sim/scripts/move_object.py
> +            model_dist = 5;
In the else case, the ModelState cannot be retrieved....I think in this case, the object.model is does not exist (?) and we do not want to stop....thus we would set the model_dist to something ```float('inf')```

2016-12-09 11:30 UTC, ipa-fxm commented
I addressed @ipa-fmw's comments in #125, i.e.
 - introduce stop_distance (--stop-distance)
 - able to pass a list of objects (--stop-objects); -o/--object is not possible anymore
 - stop also on circle and polygon

@fmw-hb please test #125

2016-12-09 17:16 UTC, merged