Fix external environment simulation
ipa320/cob_simulation pull request #148
Opened 2017-05-30 08:34 UTC by ipa-mjp

2017-05-30 09:31 UTC, fmessmer reviewed
please consider my comments...

Should be squash-merged thereafter!

2017-05-30 09:31 UTC, ipa-fxm commented on cob_gazebo_worlds/launch/world.launch
> +		<arg name="pkg_env_config" value="$(arg pkg_env_config)"/>
please revert these lines and add a `upload_navigation_goals.launch` to your external `pkg_env_config` package

2017-05-30 09:31 UTC, ipa-fxm commented on cob_gazebo_worlds/launch/world.launch
> +		<arg name="pkg_env_config" value="$(arg pkg_env_config)"/>
please revert these lines and add a `upload_object_locations.launch` to your external `pkg_env_config` package

2017-05-30 09:31 UTC, ipa-fxm commented on cob_gazebo_worlds/launch/world.launch
> +	</include>
please revert these lines and add a `launch/$(arg robot_env).xml` to your external `pkg_env_config` package

then you do not need to pass `pkg_gazebo_worlds` to all the other `*.xml` files in this package

2017-05-30 09:31 UTC, fmessmer requested changes
see above

2017-05-30 11:13 UTC, ipa-mjp commented on cob_gazebo_worlds/launch/world.launch
> +		<arg name="pkg_env_config" value="$(arg pkg_env_config)"/>
In order to avoid copy of that file in the external package. I added this way. Is this wrong?

2017-05-30 11:28 UTC, ipa-fxm commented on cob_gazebo_worlds/launch/world.launch
> +		<arg name="pkg_env_config" value="$(arg pkg_env_config)"/>
well, it adds an argument to a lot of files without being used there...

maybe we should call the `upload_navigation_goal.launch` and `upload_object_locations.launch` directly from `cob_bringup_sim/launch/robot.launch`...
this way, we could actually get rid of the dependency to `cob_default_env_config` within `cob_gazebo_worlds`

2017-05-31 06:33 UTC, ipa-fxm commented on cob_gazebo_worlds/launch/world.launch
> +		<arg name="pkg_env_config" value="$(arg pkg_env_config)"/>
the unused argument also breaks the launch file checks...I'll propose something...

2017-05-31 13:04 UTC, mjpatell commented on cob_gazebo_worlds/launch/world.launch
> +		<arg name="pkg_env_config" value="$(arg pkg_env_config)"/>
Our stuff works fine from our environment. So you can close this request.
Thank you.

2017-05-31 13:08 UTC, ipa-fxm commented
happy to hear...

2017-05-31 13:08 UTC, closed without merging